# Generated by Django 5.2.10 on 2026-02-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='driver_name',
            new_name='driver_name_id',
        ),
    ]
