# Generated by Django 5.2.10 on 2026-04-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_driver_name_alter_ride_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='driver_name_id',
            new_name='driver',
        ),
    ]
