# Generated by Django 5.2.10 on 2026-05-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_rename_driver_name_id_ride_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'requested'), ('assigned', 'Assigned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
