# Generated by Django 5.2.10 on 2026-06-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='rejected_by',
            field=models.ManyToManyField(blank=True, related_name='rejected_rides', to='rides.driver'),
        ),
    ]
