# Generated by Django 5.2.10 on 2026-06-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_ride_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='accepted_by',
            field=models.ManyToManyField(blank=True, related_name='accepted_rides', to='rides.driver'),
        ),
    ]
